#!/usr/bin/env bash

echo '\n Installing Xcode Tools'
xcode-select --install

echo '\n Building Homebrew'
sudo chown -R $USER /usr/local
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew bundle
brew cleanup

echo '\n Installing ZSH'
rm -rf $HOME/.oh-my-zsh
rm $HOME/.zshrc
git clone git://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh
ln -s $HOME/dotfiles/zsh/.zshrc $HOME/.zshrc
ln -sf $HOME/dotfiles/zsh/theme $HOME/.oh-my-zsh/themes/zesty.zsh-theme
chsh -s /bin/zsh
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

echo '\n Setting up git'
ln -sf $HOME/dotfiles/git/.gitconfig $HOME/.gitconfig
ln -sf $HOME/dotfiles/git/.gitignore_global $HOME/.gitignore_global

echo '\n Installing NVM'
export NVM_DIR="$HOME/.nvm" && (
  git clone https://github.com/creationix/nvm.git "$NVM_DIR"
  cd "$NVM_DIR"
  git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" origin`
) && . "$NVM_DIR/nvm.sh"
nvm install 6
npm install -g gulp bower np nodemon statik electron react-native-cli

echo '\n Installing RVM'
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
curl -sSL https://get.rvm.io | bash -s stable --ruby -- --ignore-dotfiles
echo "rvm_silence_path_mismatch_check_flag=1" >> $HOME/.rvmrc # shuts up rvm complaining about not being first in PATH
