#!/usr/bin/env bash

echo 'Installing Xcode Tools'
xcode-select --install

echo "Install and Set San Francisco as System Font"
ruby -e "$(curl -fsSL https://raw.github.com/wellsriley/YosemiteSanFranciscoFont/master/install)"

echo 'Installing ZSH'
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
ln -sf ./zsh/.zshrc ~/.zshrc
ln -sf ./zsh/zesty.zsh-theme ~/.oh-my-zsh/themes
chsh -s /bin/zsh

echo 'Setting up git'
ln -sf ./git/.gitconfig ~/.gitconfig

echo 'Installing NVM'
export NVM_DIR="$HOME/.nvm" && (
  git clone https://github.com/creationix/nvm.git "$NVM_DIR"
  cd "$NVM_DIR"
  git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" origin`
) && . "$NVM_DIR/nvm.sh"
nvm install 6

echo 'Installing RVM'
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
curl -sSL https://get.rvm.io | bash -s stable --ruby

echo 'Bundling Homebrew'
brew bundle
brew cleanup
