#!/usr/bin/env bash

echo '\n Installing Xcode Tools'
xcode-select --install

echo '\n Building Homebrew'
sudo chown -R $USER /usr/local
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew bundle
brew cleanup

echo '\n Installing ZSH'
rm -rf ~/.oh-my-zsh
rm ~/.zshrc
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
ln -s ~/dotfiles/zsh/.zshrc ~/.zshrc
ln -sf ~/dotfiles/zsh/zesty.zsh-theme ~/.oh-my-zsh/themes/
chsh -s /bin/zsh
git clone git://github.com/zsh-users/zsh-syntax-highlighting $ZSH_CUSTOM/plugins/zsh-syntax-highlighting
git clone git://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions

echo '\n Setting up git'
ln -sf ~/dotfiles/git/.gitconfig ~/.gitconfig
ln -sf ~/dotfiles/git/.gitignore_global ~/.gitignore_global

echo '\n Setting up vim'
ln -sf ~/dotfiles/vim/.vim ~
ln -sf ~/dotfiles/vim/.vimrc ~

echo '\n Installing NVM'
export NVM_DIR="~/.nvm" && (
  git clone https://github.com/creationix/nvm.git "$NVM_DIR"
  cd "$NVM_DIR"
  git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" origin`
) && . "$NVM_DIR/nvm.sh"
nvm install 6
npm install -g np nodemon statik electron react-native-cli

echo '\n Installing latest stable ruby'
rbenv install stable
